import palette, { PALETTE_TONE_TYPES, PALETTE_TYPES } from '@styles/palette';

const PRIMARY = 'primary';
const PRIMARY_CONTAINER = 'primary-container';
const SECONDARY = 'secondary';
const SECONDARY_CONTAINER = 'secondary-container';
const TERTIARY = 'tertiary';
const TERTIARY_CONTAINER = 'tertiary-container';
const SURFACE = 'surface';
const SURFACE_VARIANT = 'surface-variant';
const BACKGROUND = 'background';
const ERROR = 'error';
const ERROR_CONTAINER = 'error-container';
const ON_PRIMARY = 'on-primary';
const ON_PRIMARY_CONTAINER = 'on-primary-container';
const ON_SECONDARY = 'on-secondary';
const ON_SECONDARY_CONTAINER = 'on-secondary-container';
const ON_TERTIARY = 'on-tertiary';
const ON_TERTIARY_CONTAINER = 'on-tertiary-container';
const ON_SURFACE = 'on-surface';
const ON_SURFACE_VARIANT = 'on-surface-variant';
const ON_ERROR = 'on-error';
const ON_ERROR_CONTAINER = 'on-error-container';
const ON_BACKGROUND = 'on-background';
const OUTLINE = 'outline';
const OUTLINE_VARIANT = 'outline-variant';
const SHADOW = 'shadow';
const SURFACE_TINT = 'surface-tint';
const INVERSE_SURFACE = 'inverse-surface';
const INVERSE_ON_SURFACE = 'inverse-on-surface';
const INVERSE_PRIMARY = 'inverse-primary';
const SCRIM = 'scrim';

export const COLOR_TYPES = {
  PRIMARY,
  PRIMARY_CONTAINER,
  SECONDARY,
  SECONDARY_CONTAINER,
  TERTIARY,
  TERTIARY_CONTAINER,
  SURFACE,
  SURFACE_VARIANT,
  BACKGROUND,
  ERROR,
  ERROR_CONTAINER,
  ON_PRIMARY,
  ON_PRIMARY_CONTAINER,
  ON_SECONDARY,
  ON_SECONDARY_CONTAINER,
  ON_TERTIARY,
  ON_TERTIARY_CONTAINER,
  ON_SURFACE,
  ON_SURFACE_VARIANT,
  ON_ERROR,
  ON_ERROR_CONTAINER,
  ON_BACKGROUND,
  OUTLINE,
  OUTLINE_VARIANT,
  SHADOW,
  SURFACE_TINT,
  INVERSE_SURFACE,
  INVERSE_ON_SURFACE,
  INVERSE_PRIMARY,
  SCRIM,
};

export const getColor = (props) => {
  const { theme, color = PRIMARY } = props;
  return theme.color[color];
};

const color = {
  dark: {
    [PRIMARY]: palette[PALETTE_TYPES.PRIMARY][PALETTE_TONE_TYPES.TONE_80],
    [PRIMARY_CONTAINER]:
      palette[PALETTE_TYPES.PRIMARY][PALETTE_TONE_TYPES.TONE_30],
    [SECONDARY]: palette[PALETTE_TYPES.SECONDARY][PALETTE_TONE_TYPES.TONE_80],
    [SECONDARY_CONTAINER]:
      palette[PALETTE_TYPES.SECONDARY][PALETTE_TONE_TYPES.TONE_30],
    [TERTIARY]: palette[PALETTE_TYPES.TERTIARY][PALETTE_TONE_TYPES.TONE_80],
    [TERTIARY_CONTAINER]:
      palette[PALETTE_TYPES.TERTIARY][PALETTE_TONE_TYPES.TONE_30],
    [SURFACE]: palette[PALETTE_TYPES.NEUTRAL][PALETTE_TONE_TYPES.TONE_10],
    [SURFACE_VARIANT]:
      palette[PALETTE_TYPES.NEUTRAL_VARIANT][PALETTE_TONE_TYPES.TONE_30],
    [BACKGROUND]: palette[PALETTE_TYPES.NEUTRAL][PALETTE_TONE_TYPES.TONE_10],
    [ERROR]: palette[PALETTE_TYPES.ERROR][PALETTE_TONE_TYPES.TONE_80],
    [ERROR_CONTAINER]: palette[PALETTE_TYPES.ERROR][PALETTE_TONE_TYPES.TONE_30],
    [ON_PRIMARY]: palette[PALETTE_TYPES.PRIMARY][PALETTE_TONE_TYPES.TONE_20],
    [ON_PRIMARY_CONTAINER]:
      palette[PALETTE_TYPES.PRIMARY][PALETTE_TONE_TYPES.TONE_90],
    [ON_SECONDARY]:
      palette[PALETTE_TYPES.SECONDARY][PALETTE_TONE_TYPES.TONE_20],
    [ON_SECONDARY_CONTAINER]:
      palette[PALETTE_TYPES.SECONDARY][PALETTE_TONE_TYPES.TONE_90],
    [ON_TERTIARY]: palette[PALETTE_TYPES.TERTIARY][PALETTE_TONE_TYPES.TONE_20],
    [ON_TERTIARY_CONTAINER]:
      palette[PALETTE_TYPES.TERTIARY][PALETTE_TONE_TYPES.TONE_90],
    [ON_SURFACE]: palette[PALETTE_TYPES.NEUTRAL][PALETTE_TONE_TYPES.TONE_90],
    [ON_SURFACE_VARIANT]:
      palette[PALETTE_TYPES.NEUTRAL_VARIANT][PALETTE_TONE_TYPES.TONE_80],
    [ON_ERROR]: palette[PALETTE_TYPES.ERROR][PALETTE_TONE_TYPES.TONE_20],
    [ON_ERROR_CONTAINER]:
      palette[PALETTE_TYPES.ERROR][PALETTE_TONE_TYPES.TONE_90],
    [ON_BACKGROUND]: palette[PALETTE_TYPES.NEUTRAL][PALETTE_TONE_TYPES.TONE_90],
    [OUTLINE]:
      palette[PALETTE_TYPES.NEUTRAL_VARIANT][PALETTE_TONE_TYPES.TONE_60],
    [OUTLINE_VARIANT]:
      palette[PALETTE_TYPES.NEUTRAL_VARIANT][PALETTE_TONE_TYPES.TONE_30],
    [SHADOW]: palette[PALETTE_TYPES.NEUTRAL][PALETTE_TONE_TYPES.TONE_0],
    [SURFACE_TINT]: palette[PALETTE_TYPES.PRIMARY][PALETTE_TONE_TYPES.TONE_40],
    [INVERSE_SURFACE]:
      palette[PALETTE_TYPES.NEUTRAL][PALETTE_TONE_TYPES.TONE_90],
    [INVERSE_ON_SURFACE]:
      palette[PALETTE_TYPES.NEUTRAL][PALETTE_TONE_TYPES.TONE_20],
    [INVERSE_PRIMARY]:
      palette[PALETTE_TYPES.PRIMARY][PALETTE_TONE_TYPES.TONE_40],
    [SCRIM]: palette[PALETTE_TYPES.NEUTRAL][PALETTE_TONE_TYPES.TONE_0],
  },
  light: {
    [PRIMARY]: palette[PALETTE_TYPES.PRIMARY][PALETTE_TONE_TYPES.TONE_40],
    [PRIMARY_CONTAINER]:
      palette[PALETTE_TYPES.PRIMARY][PALETTE_TONE_TYPES.TONE_90],
    [SECONDARY]: palette[PALETTE_TYPES.SECONDARY][PALETTE_TONE_TYPES.TONE_40],
    [SECONDARY_CONTAINER]:
      palette[PALETTE_TYPES.SECONDARY][PALETTE_TONE_TYPES.TONE_90],
    [TERTIARY]: palette[PALETTE_TYPES.TERTIARY][PALETTE_TONE_TYPES.TONE_40],
    [TERTIARY_CONTAINER]:
      palette[PALETTE_TYPES.TERTIARY][PALETTE_TONE_TYPES.TONE_90],
    [SURFACE]: palette[PALETTE_TYPES.NEUTRAL][PALETTE_TONE_TYPES.TONE_99],
    [SURFACE_VARIANT]:
      palette[PALETTE_TYPES.NEUTRAL_VARIANT][PALETTE_TONE_TYPES.TONE_90],
    [BACKGROUND]: palette[PALETTE_TYPES.NEUTRAL][PALETTE_TONE_TYPES.TONE_99],
    [ERROR]: palette[PALETTE_TYPES.ERROR][PALETTE_TONE_TYPES.TONE_40],
    [ERROR_CONTAINER]: palette[PALETTE_TYPES.ERROR][PALETTE_TONE_TYPES.TONE_90],
    [ON_PRIMARY]: palette[PALETTE_TYPES.PRIMARY][PALETTE_TONE_TYPES.TONE_100],
    [ON_PRIMARY_CONTAINER]:
      palette[PALETTE_TYPES.PRIMARY][PALETTE_TONE_TYPES.TONE_10],
    [ON_SECONDARY]:
      palette[PALETTE_TYPES.SECONDARY][PALETTE_TONE_TYPES.TONE_100],
    [ON_SECONDARY_CONTAINER]:
      palette[PALETTE_TYPES.SECONDARY][PALETTE_TONE_TYPES.TONE_10],
    [ON_TERTIARY]: palette[PALETTE_TYPES.TERTIARY][PALETTE_TONE_TYPES.TONE_100],
    [ON_TERTIARY_CONTAINER]:
      palette[PALETTE_TYPES.TERTIARY][PALETTE_TONE_TYPES.TONE_10],
    [ON_SURFACE]: palette[PALETTE_TYPES.NEUTRAL][PALETTE_TONE_TYPES.TONE_10],
    [ON_SURFACE_VARIANT]:
      palette[PALETTE_TYPES.NEUTRAL_VARIANT][PALETTE_TONE_TYPES.TONE_30],
    [ON_ERROR]: palette[PALETTE_TYPES.ERROR][PALETTE_TONE_TYPES.TONE_100],
    [ON_ERROR_CONTAINER]:
      palette[PALETTE_TYPES.ERROR][PALETTE_TONE_TYPES.TONE_10],
    [ON_BACKGROUND]: palette[PALETTE_TYPES.NEUTRAL][PALETTE_TONE_TYPES.TONE_10],
    [OUTLINE]:
      palette[PALETTE_TYPES.NEUTRAL_VARIANT][PALETTE_TONE_TYPES.TONE_50],
    [OUTLINE_VARIANT]:
      palette[PALETTE_TYPES.NEUTRAL_VARIANT][PALETTE_TONE_TYPES.TONE_80],
    [SHADOW]: palette[PALETTE_TYPES.NEUTRAL][PALETTE_TONE_TYPES.TONE_0],
    [SURFACE_TINT]: palette[PALETTE_TYPES.PRIMARY][PALETTE_TONE_TYPES.TONE_40],
    [INVERSE_SURFACE]:
      palette[PALETTE_TYPES.NEUTRAL][PALETTE_TONE_TYPES.TONE_20],
    [INVERSE_ON_SURFACE]:
      palette[PALETTE_TYPES.NEUTRAL][PALETTE_TONE_TYPES.TONE_95],
    [INVERSE_PRIMARY]:
      palette[PALETTE_TYPES.PRIMARY][PALETTE_TONE_TYPES.TONE_80],
    [SCRIM]: palette[PALETTE_TYPES.NEUTRAL][PALETTE_TONE_TYPES.TONE_0],
  },
};

export default color;
